[package]
name = "net_topo"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
serde_json = "1.0"

[dev-dependencies]
tokio-test = "0.4"

